# Generated by Django 6.0.3 on 2026-03-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionhistory',
            name='action_type',
            field=models.CharField(choices=[('creation', 'Création'), ('affectation', 'Affectation'), ('changement_status', 'Changement de statut'), ('resolution', 'Résolution')], default='changement_status', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
