# Generated by Django 6.0.3 on 2026-03-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_category_systemsettings_report_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
