# Generated by Django 6.0.3 on 2026-03-28 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_interventionhistory_action_type_report_resolved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category_type',
            field=models.CharField(choices=[('pothole', 'Nid de poule'), ('lighting', 'Éclairage'), ('waste', 'Déchets'), ('water', 'Fuite eau'), ('vandalism', 'Vandalisme'), ('other', 'Autre')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
